# Generated by Django 2.2.12 on 2020-04-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_domain', models.CharField(max_length=21)),
                ('team_name', models.CharField(max_length=100)),
                ('team_description', models.CharField(max_length=100, null=True)),
                ('team_discoverability', models.CharField(max_length=30, null=True)),
                ('team_id', models.CharField(max_length=30, null=True)),
                ('course_sis_id', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=30)),
            ],
            options={
                'db_table': 'slack_workspace',
            },
        ),
        migrations.CreateModel(
            name='SlackWorkspaceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('regular', 'regular'), ('owner', 'owner'), ('admin', 'admin')], default='regular', max_length=20)),
                ('univ_id', models.CharField(max_length=10)),
                ('slack_user_id', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('slack_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='slack_provisioning.SlackWorkspace')),
            ],
            options={
                'db_table': 'slack_workspace_member',
            },
        ),
    ]
